# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96957a6c915db8d9b86db9250673eaddf9ac3db691c9ec86fc05c14a9090f7d9d0c121c9af1594c7841828d3f40bb03aa649bdb5572cba5e312ede2c481eadcc

test:
  secret_key_base: cc997ab094dac33862e961f8b5eef4495787cd946fd7b8390ffbd51de6547258884b46a67348bbdb5fbf7a8bf6939369622837b219830167eaa347a997be2296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
